"""v0.6 LIVE semantic baseline: real model responses, read back offline.

tests/fixtures/recordings/live/ holds REAL exchanges recorded on 2026-10-04
through Vercel AI Gateway (`scripts/record_live_baseline.py`), routed to
Anthropic: Claude Haiku 4.5 (fast tier) and Claude Sonnet 5.5 (strong tier).
Unlike tests/fixtures/recordings/*.jsonl (synthetic, scripted), nothing here
is fabricated. Replay never touches the network; these tests also block
sockets to prove it.

v0.7 changed the judgment context and prompt, so these v0.6 requests no
longer replay through the current pipeline. Their exchanges are still real
evidence: `semantic.recorded.recorded_judgments` rebuilds and re-validates
every judgment they contain. docs/baselines/live_v0.6.md is a frozen
historical report (generated by v0.6 from these recordings).

Never re-record over these files; `record_live_baseline.py` refuses to.
"""

import socket

import pytest

from atlas_amazon.research import load_scenario
from atlas_amazon.semantic import evaluate_judgments, find_secrets
from atlas_amazon.semantic.recorded import final_judgments, recorded_judgments
from atlas_amazon.semantic.records import ChecksummedJsonl
from atlas_amazon.semantic.tiers import FAST, STRONG
from atlas_amazon.semantic.usage import measured_recording_cost
from semantic_helpers import RECORDINGS, SCENARIOS
from test_examples import ROOT

LIVE = RECORDINGS / "live"
NAMES = ["book_cozy_mystery", "physical_water_bottle"]
RECORDED_ON = "2026-10-04"


@pytest.fixture(autouse=True)
def no_network(monkeypatch):
    def refuse(*args, **kwargs):
        raise OSError("network access is disabled in live-replay tests")

    monkeypatch.setattr(socket, "socket", refuse)
    monkeypatch.setattr(socket, "create_connection", refuse)


V06_PROMPT = "judgment_batch-v1"


def v06_judgments(name):
    return recorded_judgments(LIVE / f"{name}.jsonl", prompt_version=V06_PROMPT)


def fixture_run(name):
    return load_scenario(SCENARIOS / f"{name}.json").run()


@pytest.mark.parametrize("name", NAMES)
def test_recordings_are_real_gateway_exchanges(name):
    records = ChecksummedJsonl(LIVE / f"{name}.jsonl").read()
    assert records and not find_secrets(records)
    for r in records:
        response = r["response"]
        assert response["synthetic"] is False and response["transport"] == "vercel-ai-gateway"
        assert response["model"] in (FAST.model, STRONG.model)
        assert response["responded_at"].startswith(RECORDED_ON)
        assert r["request"]["providerOptions"] == {"gateway": {"only": ["anthropic"]}}
        assert response["usage"]["input_tokens"] > 0


def test_live_usage_matches_what_was_measured():
    book = measured_recording_cost(LIVE / "book_cozy_mystery.jsonl")
    bottle = measured_recording_cost(LIVE / "physical_water_bottle.jsonl")
    assert (book.calls, bottle.calls) == (3, 5)
    assert book.cost_usd == pytest.approx(0.022479)
    assert bottle.cost_usd == pytest.approx(0.033219)
    assert book.cost_usd + bottle.cost_usd < 0.25  # the hard cap of the run
    assert (bottle.input_tokens, bottle.output_tokens) == (11602, 3049)
    assert bottle.by_model == {FAST.model: 3, STRONG.model: 2}


@pytest.mark.parametrize(
    ("name", "count"), [("book_cozy_mystery", 37), ("physical_water_bottle", 48)]
)
def test_every_recorded_judgment_rebuilds_and_validates(name, count):
    final = final_judgments(v06_judgments(name))
    assert len(final) == count
    assert all(j.prompt_version == V06_PROMPT for j in final)
    assert all(
        set(j.input["context"]) == {"product_title", "seeds"}
        for j in final
        if j.type.value != "equivalence"
    )  # the v0.6 context


def test_silently_omitted_items_were_caught_and_escalated():
    """Haiku skipped 2 of 23 items in one batch; Sonnet answered them in a later call."""
    recorded = v06_judgments("physical_water_bottle")
    strong = [r for r in recorded if r.requested_model == STRONG.model]
    assert sorted((r.judgment.type.value, r.judgment.subject) for r in strong) == [
        ("intent", "insulated water bottle"),
        ("relevance", "insulated water bottle"),
    ]
    fast_keys = {
        (r.judgment.type.value, r.judgment.input_hash)
        for r in recorded
        if r.requested_model == FAST.model
    }
    assert not {(r.judgment.type.value, r.judgment.input_hash) for r in strong} & fast_keys


@pytest.mark.parametrize(
    ("name", "expected"),
    [
        (
            "book_cozy_mystery",
            {"relevance": (8, 11), "intent": (1, 4), "entity": (2, 3), "equivalence": (1, 1)},
        ),
        (
            "physical_water_bottle",
            {"relevance": (10, 12), "intent": (3, 5), "entity": (6, 6), "equivalence": (2, 2)},
        ),
    ],
)
def test_documented_v06_agreement_is_reproduced(name, expected):
    fixture = load_scenario(SCENARIOS / f"{name}.json").run()
    # v0.6 runs also used deterministic rule judgments (unchanged since); recordings
    # hold only model exchanges.
    rules = [j for j in fixture.judgments if j.provider == "rules"]
    report = evaluate_judgments(final_judgments(v06_judgments(name)) + rules, fixture.judgments)
    assert {t.type.value: (t.agreed, t.compared) for t in report.by_type} == expected


def test_strong_tier_probe_recording():
    [r] = ChecksummedJsonl(LIVE / "gateway_strong_probe.jsonl").read()
    assert r["request"]["thinking"] == {"type": "between_tools"}
    assert r["request"]["model"] == STRONG.model and r["response"]["text"] == '{"ok":true}'


def test_frozen_v06_report_is_kept():
    text = (ROOT / "docs" / "baselines" / "live_v0.6.md").read_text(encoding="utf-8")
    assert "LIVE results" in text and "**$0.0557**" in text
